# Generated by Django 5.1 on 2024-08-11 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_bannedusers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannedusers",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="banned_users",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
