# Generated by Django 5.1 on 2024-08-11 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("snippets", "0003_alter_bannedusers_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedUser",
            fields=[
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="banned_users",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[(1, "BANNED"), (2, "SQUASHED")],
                        default="BANNED",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="BannedUsers",
        ),
    ]
