# Generated by Django 5.1 on 2024-08-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0004_banneduser_delete_bannedusers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banneduser",
            name="status",
            field=models.CharField(
                choices=[("BANNED", "BANNED"), ("SQUASHED", "SQUASHED")],
                default="BANNED",
                max_length=100,
            ),
        ),
    ]
